modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "JosephVStalin"
description = '''
${description}
'''

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersionVirtual},)"
ordering = "NONE"
side = "BOTH"
